set nocompatible
set backspace=indent,eol,start
set history=50
set ruler
set nomodeline

if has("syntax")
  syntax on
endif

filetype plugin indent on

set ic
set nu
set paste
set ai
set si
set wrap!
set hlsearch
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

highlight Comment ctermbg=DarkGray
highlight Constant ctermbg=Blue
highlight Normal ctermbg=Black
highlight NonText ctermbg=Black
highlight Special ctermbg=DarkMagenta
highlight Cursor ctermbg=Green

if has("autocmd")
   augroup redhat
   autocmd!
   " In text files, always limit the width of text to 78 characters
   autocmd BufRead *.txt set tw=78
   " Restore the last cursor position.
   autocmd BufReadPost *
   \ if line("'\"") > 0 && line ("'\"") <= line("$") |
   \   exe "normal! g'\"" |
   \ endif
   " Avoid swapfiles on common mount points.
   autocmd BufNewFile,BufReadPre /media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
   " Start spec files from the system template.
   autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
   augroup END
endif
