FROM centos:7

RUN cat > /etc/yum.repos.d/CentOS-Base.repo <<'EOF'
[base]
name=CentOS-7 - Base
baseurl=http://vault.centos.org/7.9.2009/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

[updates]
name=CentOS-7 - Updates
baseurl=http://vault.centos.org/7.9.2009/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

[extras]
name=CentOS-7 - Extras
baseurl=http://vault.centos.org/7.9.2009/extras/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
EOF

RUN yum install -y \
        ca-certificates \
        curl \
        epel-release \
        file \
        findutils \
        git \
        gzip \
        iproute \
        less \
        net-tools \
        python3 \
        procps-ng \
        rsync \
        sudo \
        tar \
        unzip \
        vim-minimal \
        wget \
        which \
        xz \
        zstd \
        zip \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN useradd -m -s /bin/bash -G wheel hyunsuk \
    && echo 'hyunsuk ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/hyunsuk \
    && chmod 0440 /etc/sudoers.d/hyunsuk \
    && mkdir -p /home/hyunsuk/.local/bin /home/hyunsuk/bin /home/hyunsuk/.cache /home/hyunsuk/shared /home/hyunsuk/repos \
    && chown -R hyunsuk:hyunsuk /home/hyunsuk

USER hyunsuk
WORKDIR /home/hyunsuk

CMD ["sleep", "infinity"]
